In [ ]:
import pandas as pd
import numpy as np

In [4]:
cpi = pd.read_csv('cpi.csv')
fx = pd.read_csv('fx.csv')
rates = pd.read_csv('rates.csv')

display(cpi.head())
display(fx.head())
display(rates.head())

,Estados Unidos,Europa,Reino Unido,Japao,China,Suica,Australia,Canada,Coreia do Sul,Noruega,Suecia,Mexico,India,Brasil
0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1,1.000331,1.010996,1.004494,1.002108,0.992949,1.001370,1.000000,1.000000,1.002023,1.005435,1.002395,1.007099,1.000000,1.005199
2,1.000561,1.015133,1.010112,1.002108,0.994975,1.009929,1.006302,1.003460,1.006057,1.007609,1.002528,1.003890,1.000000,1.010930
3,1.000041,1.016331,1.012360,1.002108,0.994002,1.008887,1.006302,1.006055,1.007074,1.002174,1.004391,0.997565,1.011765,1.015278
4,0.999623,1.016331,1.013483,1.000000,0.988004,1.004494,1.006302,1.005190,1.006057,1.001087,1.004557,0.997252,1.023530,1.015278

       EUR     BRL
0      NaN     NaN
1      NaN     NaN
2  0.69329  1.7190
3  0.69609  1.7370
4  0.69425  1.7315

,Estados Unidos,Europa,Reino Unido,Japao,China,Suica,Australia,Canada,Coreia do Sul,Noruega,Suecia,Mexico,India,Brasil
0,0.13,0.661700,0.63310,0.44,1.94,0.098743,4.1600,0.1650,2.88,2.27,0.22,5.03,6.0,8.75
1,0.16,0.644957,0.64549,0.43,1.91,0.095778,4.3275,0.2280,2.83,2.30,0.23,5.03,6.0,8.75
2,0.20,0.644700,0.65592,0.40,1.73,0.087943,4.5450,0.3375,2.51,2.39,0.29,5.03,6.0,8.80
3,0.20,0.686524,0.69713,0.39,2.02,0.081910,4.8050,0.3900,2.45,2.50,0.28,5.04,6.0,9.50
4,0.18,0.727591,0.72839,0.38,3.69,0.117741,4.8875,0.5220,2.45,2.67,0.27,5.01,6.0,10.02