In [1]:
import pandas as pd
import numpy as np

In [2]:
cpi = pd.read_csv('cpi.csv', index_col='Date', parse_dates=['Date'])
fx = pd.read_csv('fx.csv', index_col='Date', parse_dates=['Date'])
rates = pd.read_csv('rates.csv', index_col='Date', parse_dates=['Date'])

display(cpi.shape)
display(fx.shape)
display(rates.shape)

(137, 14)

(4228, 16)

(138, 14)

### Divisão dos Fatores

- Momentum: desempeho da própria moeda nos últimos 21 dias de trade (1 mês) com os últimos 62 dias (três meses)
- Fator Carry (Diferença da Taxa de Juros) -> comparar juros real com juros nominal
- Fator PPP/Taxa de Câmbio Real (câmbio + cpi)

### Momentum

In [9]:
momentum = np.log(fx.shift(21) / fx.shift(62))
momentum.dropna(inplace=True)
momentum.drop(columns='USD', inplace=True)

display(momentum.head())

,EUR,GBP,AUD,JPY,CHINA,CHF,CAD,HKD,SGD,KRW,NOK,SEK,MXN,INDIA,BRL
Date,,,,,,,,,,,,,,,
31/03/2010,0.057306,0.069748,0.008269,-0.041444,0.000088,0.042799,-0.006254,0.000889,0.002859,0.008529,0.037196,0.017623,-0.011188,-0.005633,0.007823
01/04/2010,0.047346,0.057119,0.007268,-0.033474,-0.000161,0.032175,-0.007435,0.000844,0.001688,0.001663,0.026715,0.006250,-0.008757,-0.012436,0.028938
02/04/2010,0.058615,0.063630,0.022751,-0.035218,-0.000249,0.046953,-0.000679,0.001147,0.005811,0.011522,0.044236,0.011107,-0.002515,-0.001094,0.032389
05/04/2010,0.049320,0.051579,0.010771,-0.034533,-0.000191,0.039366,-0.005042,0.000928,0.002573,0.002552,0.032680,-0.001700,-0.010723,-0.005223,0.022236
06/04/2010,0.056684,0.063255,0.018242,-0.025954,-0.000073,0.048064,-0.001847,0.000327,0.003751,0.007275,0.041840,0.004964,-0.001452,-0.002596,0.029974

### Carry

In [10]:
annual_cpi = cpi.pct_change(periods=12).dropna()

display(annual_cpi)

carry = rates.join(annual_cpi, how='inner')
display(carry)

,CPIUSD,CPIEUR,CPIGBP,CPIJPY,CPICHINA,CPICHF,CPIAUD,CPICAD,CPIKRW,CPINOK,CPISEK,CPIMXN,CPIINDIA,CPIBRL
Date,,,,,,,,,,,,,,
2011-01-02,0.021249,0.024279,0.037079,-0.005269,0.050708,0.005101,0.032563,0.021626,0.039393,0.011957,0.024650,0.035723,0.088235,0.060142
2011-01-03,0.026192,0.026815,0.035794,-0.005258,0.056046,0.010043,0.032563,0.032872,0.041332,0.009730,0.029138,0.030395,0.088235,0.062990
2011-01-04,0.030772,0.028421,0.037820,-0.004206,0.054955,0.002588,0.035491,0.032759,0.038168,0.012945,0.033414,0.033607,0.094118,0.065102
2011-01-05,0.034590,0.027317,0.037736,-0.004206,0.057048,0.003690,0.035491,0.036973,0.039116,0.016269,0.033418,0.032493,0.087209,0.065528
2011-01-06,0.035023,0.027209,0.036585,-0.003161,0.066667,0.005643,0.035491,0.030981,0.042178,0.014115,0.030797,0.032765,0.086207,0.067126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-02,0.016698,0.009373,0.007366,-0.004985,-0.004228,-0.005041,0.011150,0.010917,0.014177,0.033273,0.013574,0.037590,0.044945,0.051954
2021-01-03,0.026678,0.013317,0.010129,-0.003988,0.003219,-0.002451,0.011150,0.021962,0.019011,0.030576,0.016860,0.046668,0.056657,0.060995
2021-01-04,0.041331,0.016219,0.016575,-0.010978,0.009226,0.003279,0.038462,0.033899,0.024925,0.029543,0.022440,0.060848,0.051399,0.067593
2021-01-05,0.049183,0.019842,0.022099,-0.006994,0.016444,0.005509,0.038462,0.036002,0.026247,0.026810,0.018303,0.058938,0.052576,0.080561
2021-01-06,0.052956,0.019018,0.023897,-0.004005,0.012402,0.006045,0.038462,0.030612,0.023468,0.028546,0.013301,0.058786,0.055779,0.083471

,RATEUSD,RATEEUR,RATEGBP,RATEJPY,RATECHINA,RATECHF,RATEAUD,RATECAD,RATEKRW,RATENOK,...,CPICHINA,CPICHF,CPIAUD,CPICAD,CPIKRW,CPINOK,CPISEK,CPIMXN,CPIINDIA,CPIBRL
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-02,0.16,1.086750,0.79962,0.34000,4.84,0.139543,4.9175,0.9525,3.13,2.61,...,0.050708,0.005101,0.032563,0.021626,0.039393,0.011957,0.024650,0.035723,0.088235,0.060142
2011-01-03,0.14,1.175522,0.80913,0.33615,4.02,0.155124,4.9200,0.9260,3.35,2.62,...,0.056046,0.010043,0.032563,0.032872,0.041332,0.009730,0.029138,0.030395,0.088235,0.062990
2011-01-04,0.10,1.321211,0.82096,0.33286,3.94,0.139454,4.9000,0.9650,3.40,2.69,...,0.054955,0.002588,0.035491,0.032759,0.038168,0.012945,0.033414,0.033607,0.094118,0.065102
2011-01-05,0.09,1.425091,0.82344,0.33214,4.24,0.119450,5.0025,0.9625,3.46,2.72,...,0.057048,0.003690,0.035491,0.036973,0.039116,0.016269,0.033418,0.032493,0.087209,0.065528
2011-01-06,0.09,1.488591,0.82512,0.33214,5.91,0.102060,4.9925,0.9280,3.53,2.85,...,0.066667,0.005643,0.035491,0.030981,0.042178,0.014115,0.030797,0.032765,0.086207,0.067126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-02,0.08,-0.541100,0.05000,-0.05500,3.25,-0.732424,0.0100,0.0825,0.73,0.45,...,-0.004228,-0.005041,0.011150,0.010917,0.014177,0.033273,0.013574,0.037590,0.044945,0.051954
2021-01-03,0.07,-0.539087,0.08000,-0.06500,3.07,-0.730000,0.0300,0.1060,0.75,0.38,...,0.003219,-0.002451,0.011150,0.021962,0.019011,0.030576,0.016860,0.046668,0.056657,0.060995
2021-01-04,0.07,-0.538150,0.09000,-0.06500,2.82,-0.728541,0.0400,0.0925,0.74,0.30,...,0.009226,0.003279,0.038462,0.033899,0.024925,0.029543,0.022440,0.060848,0.051399,0.067593
2021-01-05,0.06,-0.540095,0.08000,-0.06500,2.84,-0.735221,0.0400,0.0975,0.68,0.24,...,0.016444,0.005509,0.038462,0.036002,0.026247,0.026810,0.018303,0.058938,0.052576,0.080561
2021-01-06,0.08,-0.542909,0.08000,-0.07200,2.93,-0.737727,0.0300,0.1280,0.66,0.20,...,0.012402,0.006045,0.038462,0.030612,0.023468,0.028546,0.013301,0.058786,0.055779,0.083471

In [76]:
rate_cols = carry.columns[:14]
cpi_cols  = carry.columns[14:]

paises = [c.replace('Rate', '') for c in rate_cols]

real_rate = pd.DataFrame(
    carry[rate_cols].values - carry[cpi_cols].values,
    index=carry.index,
    columns=paises
)

display(real_rate.tail())

,Estados Unidos,Europa,Reino Unido,Japao,China,Suica,Australia,Canada,Coreia do Sul,Noruega,Suecia,Mexico,India,Brasil
Date,,,,,,,,,,,,,,
2025-01-10,4.062709,2.013567,3.916597,0.80909,1.694604,-0.068032,3.550675,2.323494,2.55,4.231413,1.851079,7.86,6.760380,14.965861
2025-01-11,3.853036,2.020557,3.828856,0.80636,1.658806,-0.052577,3.640675,2.174494,2.69,4.204433,1.870020,7.66,6.760380,14.969878
2025-01-12,3.693467,2.026417,3.742598,1.07273,1.688806,-0.053843,3.700675,2.149732,2.84,4.053680,1.930113,7.52,6.754871,14.975207
2026-01-01,3.616088,2.005465,3.702598,1.11636,1.754604,-0.045053,3.770000,2.176361,2.70,4.095936,1.958588,7.34,6.751396,14.976844
2026-01-02,3.615660,2.009884,3.706313,1.23000,1.752679,-0.040567,3.960000,2.174433,2.78,4.170000,1.916872,7.33,6.748599,14.990075