In [2]:
import pandas as pd
import numpy as np

In [3]:
cpi = pd.read_csv('cpi.csv', index_col='Date', parse_dates=['Date'])
fx = pd.read_csv('fx.csv', index_col='Date', parse_dates=['Date'])
rates = pd.read_csv('rates.csv', index_col='Date', parse_dates=['Date'])

display(cpi.shape)
display(fx.shape)
display(rates.shape)

(137, 14)

(4228, 16)

(138, 14)

### Divisão dos Fatores

- Momentum: desempeho da própria moeda nos últimos 21 dias de trade (1 mês) com os últimos 62 dias (três meses)
- Fator Carry (Diferença da Taxa de Juros) -> comparar juros real com juros nominal
- Fator PPP/Taxa de Câmbio Real (câmbio + cpi)

### Momentum

In [4]:
momentum = np.log(fx.shift(21) / fx.shift(62))
momentum.dropna(inplace=True)
momentum.drop(columns='USD', inplace=True)

display(momentum.head())

,EUR,GBP,AUD,JPY,CHINA,CHF,CAD,HKD,SGD,KRW,NOK,SEK,MXN,INDIA,BRL
Date,,,,,,,,,,,,,,,
31/03/2010,0.057306,0.069748,0.008269,-0.041444,0.000088,0.042799,-0.006254,0.000889,0.002859,0.008529,0.037196,0.017623,-0.011188,-0.005633,0.007823
01/04/2010,0.047346,0.057119,0.007268,-0.033474,-0.000161,0.032175,-0.007435,0.000844,0.001688,0.001663,0.026715,0.006250,-0.008757,-0.012436,0.028938
02/04/2010,0.058615,0.063630,0.022751,-0.035218,-0.000249,0.046953,-0.000679,0.001147,0.005811,0.011522,0.044236,0.011107,-0.002515,-0.001094,0.032389
05/04/2010,0.049320,0.051579,0.010771,-0.034533,-0.000191,0.039366,-0.005042,0.000928,0.002573,0.002552,0.032680,-0.001700,-0.010723,-0.005223,0.022236
06/04/2010,0.056684,0.063255,0.018242,-0.025954,-0.000073,0.048064,-0.001847,0.000327,0.003751,0.007275,0.041840,0.004964,-0.001452,-0.002596,0.029974

### Carry

In [5]:
annual_cpi = cpi.pct_change(periods=12).dropna()

display(annual_cpi)

carry = rates.join(annual_cpi, how='inner')
display(carry.columns)

,CPIUSD,CPIEUR,CPIGBP,CPIJPY,CPICHINA,CPICHF,CPIAUD,CPICAD,CPIKRW,CPINOK,CPISEK,CPIMXN,CPIINDIA,CPIBRL
Date,,,,,,,,,,,,,,
2011-01-02,0.021249,0.024279,0.037079,-0.005269,0.050708,0.005101,0.032563,0.021626,0.039393,0.011957,0.024650,0.035723,0.088235,0.060142
2011-01-03,0.026192,0.026815,0.035794,-0.005258,0.056046,0.010043,0.032563,0.032872,0.041332,0.009730,0.029138,0.030395,0.088235,0.062990
2011-01-04,0.030772,0.028421,0.037820,-0.004206,0.054955,0.002588,0.035491,0.032759,0.038168,0.012945,0.033414,0.033607,0.094118,0.065102
2011-01-05,0.034590,0.027317,0.037736,-0.004206,0.057048,0.003690,0.035491,0.036973,0.039116,0.016269,0.033418,0.032493,0.087209,0.065528
2011-01-06,0.035023,0.027209,0.036585,-0.003161,0.066667,0.005643,0.035491,0.030981,0.042178,0.014115,0.030797,0.032765,0.086207,0.067126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-02,0.016698,0.009373,0.007366,-0.004985,-0.004228,-0.005041,0.011150,0.010917,0.014177,0.033273,0.013574,0.037590,0.044945,0.051954
2021-01-03,0.026678,0.013317,0.010129,-0.003988,0.003219,-0.002451,0.011150,0.021962,0.019011,0.030576,0.016860,0.046668,0.056657,0.060995
2021-01-04,0.041331,0.016219,0.016575,-0.010978,0.009226,0.003279,0.038462,0.033899,0.024925,0.029543,0.022440,0.060848,0.051399,0.067593
2021-01-05,0.049183,0.019842,0.022099,-0.006994,0.016444,0.005509,0.038462,0.036002,0.026247,0.026810,0.018303,0.058938,0.052576,0.080561
2021-01-06,0.052956,0.019018,0.023897,-0.004005,0.012402,0.006045,0.038462,0.030612,0.023468,0.028546,0.013301,0.058786,0.055779,0.083471

Index(['RATEUSD', 'RATEEUR', 'RATEGBP', 'RATEJPY', 'RATECHINA', 'RATECHF',
       'RATEAUD', 'RATECAD', 'RATEKRW', 'RATENOK', 'RATESEK', 'RATEMXN',
       'RATEINDIA', 'RATEBRL', 'CPIUSD', 'CPIEUR', 'CPIGBP', 'CPIJPY',
       'CPICHINA', 'CPICHF', 'CPIAUD', 'CPICAD', 'CPIKRW', 'CPINOK', 'CPISEK',
       'CPIMXN', 'CPIINDIA', 'CPIBRL'],
      dtype='object')

In [ ]:
rate_cols = carry.columns[:14]
cpi_cols  = carry.columns[14:]

real_rate = pd.DataFrame(
    carry[rate_cols].values - carry[cpi_cols].values,
    index=carry.index,
    columns=paises,
)

display(real_rate.tail())

,RATEUSD,RATEEUR,RATEGBP,RATEJPY,RATECHINA,RATECHF,RATEAUD,RATECAD,RATEKRW,RATENOK,RATESEK,RATEMXN,RATEINDIA,RATEBRL
Date,,,,,,,,,,,,,,
2021-01-02,0.063302,-0.550473,0.042634,-0.050015,3.254228,-0.727383,-0.001150,0.071583,0.715823,0.416727,-0.144874,4.292410,4.205055,1.948046
2021-01-03,0.043322,-0.552404,0.069871,-0.061012,3.066781,-0.727549,0.018850,0.084038,0.730989,0.349424,-0.176510,4.193332,4.193343,2.279005
2021-01-04,0.028669,-0.554369,0.073425,-0.054022,2.810774,-0.731820,0.001538,0.058601,0.715075,0.270457,-0.169150,4.189152,4.198601,2.682407
2021-01-05,0.010817,-0.559938,0.057901,-0.058006,2.823556,-0.740730,0.001538,0.061498,0.653753,0.213190,-0.170203,4.201062,4.197424,3.299439
2021-01-06,0.027044,-0.561927,0.056103,-0.067995,2.917598,-0.743772,-0.008462,0.097388,0.636532,0.171454,-0.172111,4.251214,4.194221,3.766529

### Volatilidade Implicita e Volatilidade Realizada

### Backtest